export default function TermsPage() {
return (
<div className="min-h-screen bg-[#f6f8f6] text-[#0e1b12] font-sans"><header className="sticky top-0 z-50 flex items-center justify-between border-b border-[#e8f3eb] px-6 py-4 lg:px-10 bg-[#f6f8f6]/95 backdrop-blur-sm"><div className="flex items-center gap-3 font-bold text-lg"></div>
    <div className="flex items-center gap-8">
      <button className="h-9 px-4 rounded bg-[#20df60] text-[#0e1b12] text-sm font-bold hover:opacity-90">
        Get Started
      </button>
    </div>
  </header>

  {/* Page Layout */}
  <div className="max-w-[1200px] mx-auto px-4 md:px-8 py-10 flex gap-12">
    
    {/* Sidebar / TOC */}
    <aside className="hidden lg:block w-64 shrink-0 sticky top-28 h-[calc(100vh-140px)]">
      <nav className="flex flex-col gap-6">
        <h2 className="text-xs font-bold uppercase tracking-wider text-[#0e1b12]/50 px-3">
          On this page
        </h2>

        <div className="flex flex-col gap-1 border-l border-[#e8f3eb] pl-3 text-sm">
          <a href="#nature" className="border-l-2 border-[#20df60] pl-3 -ml-3.5 font-medium">
            Nature of Service
          </a>
          <a href="#responsibility" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            User Responsibility
          </a>
          <a href="#limits" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Usage Limits
          </a>
          <a href="#billing" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Subscriptions & Billing
          </a>
          <a href="#refunds" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Refund Policy
          </a>
          <a href="#privacy" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Privacy & Data
          </a>
          <a href="#intellectual" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Intellectual Property
          </a>
          <a href="#termination" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Account Termination
          </a>
          <a href="#liability" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Limitation of Liability
          </a>
          <a href="#governing" className="pl-3 -ml-3.5 hover:text-[#20df60]">
            Governing Law
          </a>
        </div>
      </nav>
    </aside>

    {/* Main Content */}
    <main className="flex-1 max-w-[720px] mx-auto lg:mx-0 flex flex-col gap-10 pb-20">
      
      {/* Header */}
      <section className="border-b border-[#e8f3eb] pb-8">
        <h1 className="text-4xl md:text-5xl font-black tracking-tight">
          Terms of Service
        </h1>

        <p className="text-sm text-gray-500 mt-2">
          Last Updated: October 26, 2023
        </p>

        <p className="text-lg leading-relaxed mt-4 text-[#0e1b12]/90">
          Please read these terms carefully before using Aletheia. By accessing
          or using our service, you agree to be bound by these terms and our
          Privacy Policy. If you do not agree with any part of these terms,
          you must not access or use our service. These terms constitute a
          legally binding agreement between you and Aletheia Wellness Inc.
        </p>
      </section>

      {/* Medical Disclaimer */}
      <div className="rounded-lg bg-[#20df60]/10 border border-[#20df60]/20 p-6">
        <h3 className="font-bold text-lg mb-2">
          Important: Not a Medical Service
        </h3>
        <p className="leading-relaxed text-[#0e1b12]/80">
          Aletheia is a mental wellness tool designed for self-reflection and
          emotional support. It is <strong>not</strong> a replacement for
          professional therapy, psychiatric care, or crisis intervention.
          The AI companion is not a licensed therapist, counselor, or medical
          professional. All responses are generated by artificial intelligence
          and should not be considered as medical advice, diagnosis, or treatment.
          If you are in crisis, experiencing thoughts of self-harm, or need
          immediate assistance, contact emergency services at 911 (US) or your
          local emergency number immediately. You may also contact the National
          Suicide Prevention Lifeline at 988 for 24/7 crisis support.
        </p>
      </div>

      {/* Sections */}
      {[
        {
          id: "nature",
          title: "1. Nature of the Service",
          content: (
            <>
              <p>
                Aletheia provides voice-based AI conversations for wellness
                and reflection. It does not diagnose or treat medical conditions.
                The service utilizes advanced natural language processing and
                machine learning algorithms to generate responses based on user
                input. All interactions are generated by an automated system
                and are for informational and self-reflection purposes only.
              </p>
              <p>
                Aletheia is designed as a tool for personal growth, emotional
                awareness, and structured thinking. It should be used as a
                complement to, not a replacement for, professional mental
                health services. The AI companion is not capable of forming
                therapeutic relationships, understanding complex psychological
                conditions, or providing clinical interventions.
              </p>
              <p>
                We reserve the right to modify, suspend, or discontinue any
                feature of the service at any time without prior notice. We
                may also impose limits on certain features or restrict access
                to parts of the service without notice or liability.
              </p>
            </>
          ),
        },
        {
          id: "responsibility",
          title: "2. User Responsibility",
          content: (
            <>
              <p>
                You are responsible for maintaining the confidentiality of
                your account and credentials. You agree to immediately notify
                us of any unauthorized access to or use of your account. You
                are fully responsible for all activities that occur under your
                account. We will not be liable for any loss or damage arising
                from your failure to comply with this security obligation.
              </p>
              <p>
                You must be at least 18 years of age to use this service. By
                creating an account, you represent and warrant that you meet
                this age requirement and have the legal capacity to enter
                into these terms. If you are using the service on behalf of
                an organization, you represent that you have the authority to
                bind that organization to these terms.
              </p>
              <p>
                You agree not to use the service for any unlawful purpose or
                in any way that could damage, disable, overburden, or impair
                our servers or networks. You agree not to attempt to gain
                unauthorized access to any part of the service, other accounts,
                computer systems, or networks connected to our servers.
              </p>
              <div className="bg-gray-100 p-4 rounded border-l-4 border-gray-300 text-sm mt-4">
                <strong>Prohibited actions include but are not limited to:</strong>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>Using the service to generate harmful, abusive, or illegal content</li>
                  <li>Attempting to reverse engineer, decompile, or hack the service</li>
                  <li>Sharing your account credentials with third parties</li>
                  <li>Using automated scripts or bots to access the service</li>
                  <li>Impersonating any person or entity or falsely stating your affiliation</li>
                  <li>Using the service for commercial purposes without explicit written permission</li>
                </ul>
              </div>
            </>
          ),
        },
        {
          id: "limits",
          title: "3. Usage Limits & Fair Use",
          content: (
            <>
              <p>
                Usage limits may apply to ensure fair access and prevent abuse.
                These limits are designed to maintain service quality for all
                users and prevent excessive consumption of resources. The specific
                limits depend on your subscription plan:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>
                  <strong>Guided Plan:</strong> Up to 60 minutes of voice interaction
                  per day, with a maximum of 30 sessions per month
                </li>
                <li>
                  <strong>Extended Plan:</strong> Up to 8 hours of voice interaction
                  per day, with a maximum of 200 sessions per month
                </li>
              </ul>
              <p className="mt-4">
                Unusual usage patterns, such as extremely rapid-fire requests,
                automated querying, or attempts to circumvent rate limiting,
                may result in throttling, suspension, or termination of your
                account without notice. We reserve the right to adjust these
                limits at our discretion to maintain service stability.
              </p>
              <p>
                Daily caps reset at midnight UTC. Sessions are counted as
                continuous interactions with the AI companion, with brief pauses
                (under 5 minutes) considered part of the same session. If you
                exceed your plan's limits, you will receive a notification and
                may be prompted to upgrade your plan or wait until the next
                billing period.
              </p>
            </>
          ),
        },
        {
          id: "billing",
          title: "4. Subscriptions & Billing",
          content: (
            <>
              <p>
                Subscriptions renew automatically unless cancelled before
                the renewal date. All subscriptions are billed in advance
                on a monthly or annual basis, depending on the plan you select.
                By providing a payment method, you represent and warrant that
                you are authorized to use the designated payment method and
                that you authorize us to charge your payment method for the
                total amount of your subscription fees.
              </p>
              <p>
                Payments are processed securely via third-party payment providers
                including Stripe and Clerk. We do not store your complete payment
                information on our servers. All payment transactions are encrypted
                using industry-standard SSL technology. You are responsible for
                maintaining accurate billing information and ensuring that your
                payment method remains valid.
              </p>
              <p>
                If a payment fails due to expired card, insufficient funds, or
                other reasons, we will attempt to process the payment again
                after 3 days. If payment continues to fail, your subscription
                may be downgraded to the free tier or suspended until payment
                is successfully processed. You can update your payment method
                at any time through your account settings.
              </p>
              <p>
                You may cancel your subscription at any time through your
                account dashboard. Cancellations take effect at the end of
                the current billing period, and you will continue to have
                access to paid features until that time. We do not provide
                refunds for partial months or unused subscription periods,
                except as outlined in our refund policy.
              </p>
            </>
          ),
        },
        {
          id: "refunds",
          title: "5. Refund Policy",
          content: (
            <>
              <p>
                We offer a 7-day money-back guarantee for first-time subscribers
                who are not satisfied with our service. To request a refund,
                you must contact our support team at support@aletheia.app within
                7 days of your initial subscription purchase. Refunds will be
                processed to your original payment method within 5-10 business
                days of approval.
              </p>
              <p>
                Renewals are generally non-refundable. However, we may consider
                refund requests on a case-by-case basis for exceptional
                circumstances, such as technical issues that prevent you from
                accessing the service for an extended period. Refund requests
                must be submitted within 30 days of the renewal charge.
              </p>
              <p>
                We reserve the right to refuse refunds if we detect abuse of
                our refund policy, including repeated subscription cancellations
                and re-subscriptions, or if we determine that you have used
                the service extensively during the refund period. Annual
                subscriptions that are cancelled after 30 days may be eligible
                for a prorated refund at our discretion.
              </p>
            </>
          ),
        },
        {
          id: "privacy",
          title: "6. Privacy & Data Protection",
          content: (
            <>
              <p>
                Your privacy is critically important to us. We collect and
                process personal data in accordance with our Privacy Policy
                and applicable data protection laws, including GDPR and CCPA.
                We collect information you provide directly, such as account
                details and conversation content, as well as technical data
                like IP addresses and device information.
              </p>
              <p>
                Voice recordings and conversation transcripts are processed
                to provide the service and may be stored for improving AI
                performance. We implement robust security measures including
                encryption at rest and in transit, access controls, and regular
                security audits. However, no system is completely secure, and
                we cannot guarantee absolute security of your data.
              </p>
              <p>
                We retain your personal data only as long as necessary to
                provide the service or as required by law. You have the right
                to access, correct, or delete your personal data. To exercise
                these rights, contact us at privacy@aletheia.app. For more
                details, please review our complete Privacy Policy.
              </p>
            </>
          ),
        },
        {
          id: "intellectual",
          title: "7. Intellectual Property",
          content: (
            <>
              <p>
                The Aletheia service, including all software, AI models,
                user interfaces, design elements, and underlying technology,
                is owned by Aletheia Wellness Inc. and is protected by
                copyright, trademark, patent, and other intellectual property
                laws. You are granted a limited, non-exclusive, non-transferable
                license to use the service for personal, non-commercial purposes.
              </p>
              <p>
                You retain ownership of the content you provide through the
                service, including voice recordings and conversation transcripts.
                By using the service, you grant us a worldwide, royalty-free
                license to use, store, and process your content to provide
                and improve our services. This license does not grant us
                ownership of your content.
              </p>
              <p>
                You may not copy, modify, distribute, sell, or lease any part
                of our service or included software without our explicit written
                permission. You may not reverse engineer or attempt to extract
                the source code of our software, unless laws prohibit these
                restrictions or you have our written permission.
              </p>
            </>
          ),
        },
        {
          id: "termination",
          title: "8. Account Termination",
          content: (
            <>
              <p>
                We reserve the right to suspend or terminate your account at
                any time for violation of these terms, illegal activity,
                or behavior that harms other users or our service. If we
                suspend or terminate your account, we will make reasonable
                efforts to notify you via email or in-app notification.
              </p>
              <p>
                Upon termination, your right to use the service immediately
                ceases. We will delete or anonymize your personal data within
                30 days of account termination, except as required by law or
                for legitimate business purposes. Content you have shared
                publicly may remain visible even after account termination.
              </p>
              <p>
                You may delete your account at any time through your account
                settings. Account deletion is permanent and cannot be reversed.
                After deletion, you will not be able to recover any data
                associated with your account.
              </p>
            </>
          ),
        },
        {
          id: "liability",
          title: "9. Limitation of Liability",
          content: (
            <>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALETHEIA,
                ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, SUPPLIERS OR
                LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
                SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT
                LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER
                INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO YOUR USE OF
                THE SERVICE.
              </p>
              <p>
                ALETHEIA'S TOTAL LIABILITY FOR ALL CLAIMS RELATED TO THE
                SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE SERVICE
                IN THE 12 MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED DOLLARS
                IF NO SUCH PAYMENTS HAVE BEEN MADE. THIS LIMITATION APPLIES
                REGARDLESS OF THE THEORY OF LIABILITY AND WHETHER OR NOT
                ALETHEIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
              </p>
              <p>
                Some jurisdictions do not allow the exclusion or limitation
                of certain damages, so the above limitations may not apply
                to you. In such jurisdictions, our liability is limited to
                the maximum extent permitted by law.
              </p>
            </>
          ),
        },
        {
          id: "governing",
          title: "10. Governing Law & Disputes",
          content: (
            <>
              <p>
                These terms are governed by the laws of the State of California,
                without regard to its conflict of law provisions. Any dispute
                arising from these terms or your use of the service will be
                resolved through binding arbitration in San Francisco, California,
                in accordance with the rules of the American Arbitration Association.
              </p>
              <p>
                You agree to submit to the personal jurisdiction of the courts
                located in San Francisco County, California for any actions not
                subject to arbitration. The United Nations Convention on Contracts
                for the International Sale of Goods does not apply to these terms.
              </p>
              <p>
                By using Aletheia, you waive any right to participate in a class
                action lawsuit or class-wide arbitration. You may opt out of this
                arbitration agreement by sending written notice to our legal team
                within 30 days of first using the service.
              </p>
            </>
          ),
        },
      ].map(({ id, title, content }) => (
        <section key={id} id={id} className="scroll-mt-32 space-y-4">
          <h2 className="text-2xl font-bold tracking-tight">{title}</h2>
          <div className="space-y-4 text-[#0e1b12]/80 leading-relaxed">
            {content}
          </div>
        </section>
      ))}

      {/* Footer */}
      <footer className="border-t border-[#e8f3eb] pt-10 mt-8 flex flex-col sm:flex-row gap-6 justify-between">
        <div className="flex gap-6 text-sm">
          <a href="/privacy" className="text-[#20df60] hover:underline">Privacy Policy</a>
          <a href="#" className="text-[#20df60] hover:underline">Community Guidelines</a>
          <a href="#" className="text-[#20df60] hover:underline">Contact Support</a>
        </div>
        <p className="text-sm text-gray-500">© 2023 Aletheia Wellness Inc.</p>
      </footer>
    </main>
  </div>
</div>

);
}